services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: cogniboard
      POSTGRES_USER: cogniboard
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cogniboard -d cogniboard"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - cogniboard-network

networks:
  cogniboard-network:
    driver: bridge
