components:
  schemas:
    ChangeTaskStatus:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          example: http://127.0.0.1:8888/v1/api/schemas/ChangeTaskStatus.json
          format: uri
          readOnly: true
          type: string
        status:
          description: New status for the task
          minLength: 1
          type: string
      required:
        - status
      type: object
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          example: http://127.0.0.1:8888/v1/api/schemas/ErrorModel.json
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          example: Property foo is required but is missing.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
          nullable: true
          type: array
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          example: https://example.com/error-log/abc123
          format: uri
          type: string
        status:
          description: HTTP status code
          example: 400
          format: int64
          type: integer
        title:
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          example: Bad Request
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          example: https://example.com/errors/example
          format: uri
          type: string
      type: object
    File:
      additionalProperties: false
      properties:
        id:
          type: string
        mime_type:
          type: string
        name:
          type: string
        size:
          format: int64
          type: integer
        uploaded_at:
          format: date-time
          type: string
      required:
        - id
        - name
        - size
        - mime_type
        - uploaded_at
      type: object
    ListTasks:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          example: http://127.0.0.1:8888/v1/api/schemas/ListTasks.json
          format: uri
          readOnly: true
          type: string
        tasks:
          items:
            $ref: "#/components/schemas/Task"
          nullable: true
          type: array
      required:
        - tasks
      type: object
    Task:
      additionalProperties: false
      properties:
        asignee:
          nullable: true
          type: string
        completed_at:
          format: date-time
          nullable: true
          type: string
        created_at:
          format: date-time
          type: string
        description:
          nullable: true
          type: string
        due_date:
          format: date-time
          nullable: true
          type: string
        files:
          items:
            $ref: "#/components/schemas/File"
          nullable: true
          type: array
        id:
          type: string
        status:
          type: string
        title:
          type: string
        updated_at:
          format: date-time
          type: string
      required:
        - files
        - id
        - title
        - description
        - due_date
        - asignee
        - created_at
        - updated_at
        - completed_at
        - status
      type: object
info:
  title: CogniBoard
  version: 0.0.1
openapi: 3.0.3
paths:
  /tasks:
    get:
      operationId: tasks
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListTasks"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Get all tasks
  /tasks/create:
    post:
      operationId: task-create
      requestBody:
        content:
          multipart/form-data:
            encoding:
              assignee_name:
                contentType: text/plain
              description:
                contentType: text/plain
              due_date:
                contentType: text/plain
              files:
                contentType: application/octet-stream
              title:
                contentType: text/plain
            schema:
              properties:
                assignee_name:
                  description: Task's asignee (if any)
                  type: string
                description:
                  description: Task's description
                  type: string
                due_date:
                  description: Task's due date (if any)
                  format: date-time
                  type: string
                files:
                  items:
                    contentEncoding: binary
                    contentMediaType: application/octet-stream
                    format: binary
                    type: string
                  type: array
                title:
                  description: Task's name
                  maxLength: 50
                  minLength: 1
                  type: string
              required:
                - title
              type: object
      responses:
        "204":
          description: No Content
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Create a task
  /tasks/{taskId}/edit:
    post:
      operationId: task-edit
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            encoding:
              assignee_name:
                contentType: text/plain
              description:
                contentType: text/plain
              due_date:
                contentType: text/plain
              files:
                contentType: application/octet-stream
              title:
                contentType: text/plain
            schema:
              properties:
                assignee_name:
                  description: Task's asignee (if any)
                  type: string
                description:
                  description: Task's description
                  type: string
                due_date:
                  description: Task's due date (if any)
                  format: date-time
                  type: string
                files:
                  items:
                    contentEncoding: binary
                    contentMediaType: application/octet-stream
                    format: binary
                    type: string
                  type: array
                title:
                  description: Task's name
                  maxLength: 50
                  minLength: 1
                  type: string
              required:
                - title
              type: object
      responses:
        "204":
          description: No Content
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Edit a task
  /tasks/{taskId}/status:
    post:
      operationId: task-change-status
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeTaskStatus"
        required: true
      responses:
        "204":
          description: No Content
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Change task status
servers:
  - url: http://127.0.0.1:8888/v1/api
