components:
  schemas:
    AssignTaskDTO:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - http://127.0.0.1:8888/v1/api/schemas/AssignTaskDTO.json
          format: uri
          readOnly: true
          type: string
        assignee_name:
          description: Name of the person to assign the task to
          minLength: 1
          type: string
      required:
        - assignee_name
      type: object
    ChangeTaskStatusDTO:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - http://127.0.0.1:8888/v1/api/schemas/ChangeTaskStatusDTO.json
          format: uri
          readOnly: true
          type: string
        status:
          description: New status for the task
          minLength: 1
          type: string
      required:
        - status
      type: object
    CreateTaskDTO:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - http://127.0.0.1:8888/v1/api/schemas/CreateTaskDTO.json
          format: uri
          readOnly: true
          type: string
        assignee_name:
          description: Task's asignee (if any)
          type: string
        description:
          description: Task's description
          type: string
        due_date:
          description: Task's due date (if any)
          format: date-time
          type: string
        title:
          description: Task's name
          maxLength: 50
          minLength: 1
          type: string
      required:
        - title
      type: object
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - http://127.0.0.1:8888/v1/api/schemas/ErrorModel.json
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          examples:
            - Property foo is required but is missing.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
          type:
            - array
            - "null"
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          examples:
            - https://example.com/error-log/abc123
          format: uri
          type: string
        status:
          description: HTTP status code
          examples:
            - 400
          format: int64
          type: integer
        title:
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          examples:
            - Bad Request
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          examples:
            - https://example.com/errors/example
          format: uri
          type: string
      type: object
    GetTasksDTO:
      additionalProperties: false
      properties:
        assignee:
          type:
            - string
            - "null"
        completed_at:
          format: date-time
          type:
            - string
            - "null"
        created_at:
          format: date-time
          type: string
        description:
          type:
            - string
            - "null"
        due_date:
          format: date-time
          type:
            - string
            - "null"
        id:
          type: string
        status:
          type: string
        title:
          type: string
      required:
        - id
        - title
        - description
        - due_date
        - assignee
        - created_at
        - completed_at
        - status
      type: object
    Tasks:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - http://127.0.0.1:8888/v1/api/schemas/Tasks.json
          format: uri
          readOnly: true
          type: string
        tasks:
          items:
            $ref: "#/components/schemas/GetTasksDTO"
          type:
            - array
            - "null"
      required:
        - tasks
      type: object
info:
  title: CogniBoard
  version: 0.0.1
openapi: 3.1.0
paths:
  /tasks:
    get:
      operationId: get-tasks
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tasks"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Get all tasks
  /tasks/create:
    post:
      operationId: create-task
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTaskDTO"
        required: true
      responses:
        "204":
          description: No Content
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Create a task
  /tasks/{taskId}/assign:
    post:
      operationId: assign-task
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssignTaskDTO"
        required: true
      responses:
        "204":
          description: No Content
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Assign a task to someone
  /tasks/{taskId}/status:
    post:
      operationId: change-task-status
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeTaskStatusDTO"
        required: true
      responses:
        "204":
          description: No Content
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Change task status
  /tasks/{taskId}/unassign:
    post:
      operationId: unassign-task
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No Content
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Unassign a task
servers:
  - url: http://127.0.0.1:8888/v1/api
