INSERT INTO tasks (
    id, 
    title, 
    description, 
    due_date, 
    assignee_name, 
    created_at, 
    updated_at, 
    completed_at, 
    status
) VALUES 
    ('1', 'Implement drag and drop functionality', 'Add smooth drag and drop between columns in the Kanban board view', '2026-05-15', 'John', NOW(), NOW(), NULL, 'in_progress'),
    ('2', 'Design user dashboard', 'Create wireframes and mockups for the main dashboard interface', '2026-05-10', 'Laura', NOW(), NOW(), NULL, 'in_review'),
    ('3', 'Add board sharing capabilities', 'Implement feature to share boards with team members with different permission levels', '2026-05-20', 'Steve', NOW(), NOW(), NULL, 'pending'),
    ('4', 'Optimize database queries', 'Improve performance of board loading and card updates', '2026-05-12', 'Alex', NOW(), NOW(), NULL, 'in_progress'),
    ('5', 'Implement user authentication', 'Set up JWT authentication and user session management', '2026-05-08', 'Mary', NOW(), NOW(), '2026-04-20', 'completed'),
    ('6', 'Create board templates', 'Design and implement reusable board templates for common use cases', '2026-05-25', 'John', NOW(), NOW(), NULL, 'pending'),
    ('7', 'Add card labels feature', 'Implement color-coded labels for better task categorization', '2026-05-18', 'Laura', NOW(), NOW(), NULL, 'in_progress'),
    ('8', 'Mobile responsive design', 'Ensure proper display and functionality on mobile devices', '2026-05-30', 'Steve', NOW(), NOW(), NULL, 'pending'),
    ('9', 'Implement activity log', 'Add tracking for all board and card changes with user attribution', '2026-05-22', 'Alex', NOW(), NOW(), NULL, 'in_review'),
    ('10', 'Add board statistics', 'Create analytics dashboard for board metrics and team productivity', '2026-05-28', 'Mary', NOW(), NOW(), NULL, 'pending'),
    ('11', 'Setup automated testing', 'Implement end-to-end testing suite for critical features', '2026-06-05', 'John', NOW(), NOW(), NULL, 'pending'),
    ('12', 'Add due date notifications', 'Implement email and in-app notifications for approaching deadlines', '2026-06-10', 'Laura', NOW(), NOW(), NULL, 'pending'),
    ('13', 'Implement card attachments', 'Add support for file attachments on cards', '2026-06-15', 'Steve', NOW(), NOW(), NULL, 'in_progress'),
    ('14', 'Create user onboarding flow', 'Design and implement guided tutorial for new users', '2026-06-20', 'Alex', NOW(), NOW(), NULL, 'in_review'),
    ('15', 'Add board export feature', 'Implement PDF and CSV export functionality for boards', '2026-06-25', 'Mary', NOW(), NOW(), NULL, 'pending'),
    ('16', 'Implement card dependencies', 'Add ability to link related cards and track dependencies', '2026-07-01', 'John', NOW(), NOW(), NULL, 'pending'),
    ('17', 'Add custom field support', 'Allow users to create custom fields for cards', '2026-07-05', 'Laura', NOW(), NOW(), NULL, 'in_progress'),
    ('18', 'Implement board archiving', 'Add functionality to archive completed boards and cards', '2026-07-10', 'Steve', NOW(), NOW(), '2026-04-19', 'completed'),
    ('19', 'Add team management features', 'Implement team creation and management functionality', '2026-07-15', 'Alex', NOW(), NOW(), NULL, 'pending'),
    ('20', 'Create API documentation', 'Document all API endpoints and integration guidelines', '2026-07-20', 'Mary', NOW(), NOW(), NULL, 'in_review');