version: '3'

tasks:
  install:
    desc: Install devbox if not already installed
    cmds:
      - |
        if ! command -v devbox &> /dev/null; then
          curl -fsSL https://get.jetpack.io/devbox | bash
        fi

  setup:
    desc: Setup development environment
    deps: [install]
    cmds:
      - devbox shell

  docker:
    desc: Start Docker services
    cmds:
      - docker compose up -d

  docker-down:
    desc: Stop docker services
    cmds:
      - docker compose down

  server:
    desc: Run the API service
    cmds:
      - go run cmd/http/main.go

  gen-hooks:
    desc: Generate React Query hooks
    dir: web
    cmds:
      - bunx orval

  web:
    desc: Start the web sever
    dir: web
    cmds:
      - bun dev

  dev:
    desc: Start development environment
    deps: [install]
    cmds:
      - task: docker
      - task: run-api