// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FilesColumns holds the columns for the "files" table.
	FilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64},
		{Name: "mime_type", Type: field.TypeString},
		{Name: "uploaded_at", Type: field.TypeTime},
	}
	// FilesTable holds the schema information for the "files" table.
	FilesTable = &schema.Table{
		Name:       "files",
		Columns:    FilesColumns,
		PrimaryKey: []*schema.Column{FilesColumns[0]},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "due_date", Type: field.TypeTime, Nullable: true},
		{Name: "assignee_name", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "in_progress", "in_review", "completed"}, Default: "pending"},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
	}
	// TaskFilesColumns holds the columns for the "task_files" table.
	TaskFilesColumns = []*schema.Column{
		{Name: "task_id", Type: field.TypeString},
		{Name: "file_id", Type: field.TypeString},
	}
	// TaskFilesTable holds the schema information for the "task_files" table.
	TaskFilesTable = &schema.Table{
		Name:       "task_files",
		Columns:    TaskFilesColumns,
		PrimaryKey: []*schema.Column{TaskFilesColumns[0], TaskFilesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_files_task_id",
				Columns:    []*schema.Column{TaskFilesColumns[0]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "task_files_file_id",
				Columns:    []*schema.Column{TaskFilesColumns[1]},
				RefColumns: []*schema.Column{FilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FilesTable,
		TasksTable,
		TaskFilesTable,
	}
)

func init() {
	TaskFilesTable.ForeignKeys[0].RefTable = TasksTable
	TaskFilesTable.ForeignKeys[1].RefTable = FilesTable
}
