/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CogniBoard
 * OpenAPI spec version: 0.0.1
 */
import {
  z as zod
} from 'zod'

/**
 * @summary Get all tasks
 */
export const tasksResponse = zod.object({
  "$schema": zod.string().url().optional(),
  "tasks": zod.array(zod.object({
  "assignee": zod.string().nullable(),
  "completed_at": zod.string().datetime().nullable(),
  "created_at": zod.string().datetime(),
  "description": zod.string().nullable(),
  "due_date": zod.string().datetime().nullable(),
  "id": zod.string(),
  "status": zod.string(),
  "title": zod.string()
})).nullable()
})


/**
 * @summary Create a task
 */
export const taskCreateBodyTitleMax = 50;


export const taskCreateBody = zod.object({
  "assignee_name": zod.string().optional(),
  "description": zod.string().optional(),
  "due_date": zod.string().datetime().optional(),
  "title": zod.string().min(1).max(taskCreateBodyTitleMax)
})


/**
 * @summary Edit a task
 */
export const taskEditParams = zod.object({
  "taskId": zod.string()
})

export const taskEditBodyTitleMax = 50;


export const taskEditBody = zod.object({
  "assignee_name": zod.string().optional(),
  "description": zod.string().optional(),
  "due_date": zod.string().datetime().optional(),
  "status": zod.string().optional(),
  "title": zod.string().max(taskEditBodyTitleMax).optional()
})


/**
 * @summary Change task status
 */
export const taskChangeStatusParams = zod.object({
  "taskId": zod.string()
})

export const taskChangeStatusBody = zod.object({
  "status": zod.string().min(1)
})


