// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/DeluxeOwl/cogniboard/internal/postgres/ent/file"
	"github.com/DeluxeOwl/cogniboard/internal/postgres/ent/schema"
	"github.com/DeluxeOwl/cogniboard/internal/postgres/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescUploadedAt is the schema descriptor for uploaded_at field.
	fileDescUploadedAt := fileFields[4].Descriptor()
	// file.DefaultUploadedAt holds the default value on creation for the uploaded_at field.
	file.DefaultUploadedAt = fileDescUploadedAt.Default.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[5].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[6].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
}
